r"""What a read costs the database, counted rather than timed.

Every other database test here asserts what an endpoint *answers*. This one asserts what it
*does*: how many statements it issues, and whether that number moves with the size of the
answer. Those are different failures. An N+1 returns exactly the right JSON — it is invisible
to every assertion about content, and it is the single defect most likely to make a correct
API unusable on a real estate.

**Counted, never timed.** A millisecond is a fact about the machine the suite happened to run
on, and a threshold in milliseconds is a test that fails on a busy laptop and passes on a
fast one until nobody trusts it. A statement count is a fact about the code: it is the same
number on every machine, and "this request issued nine statements for a hundred rows and nine
for one" is the property an N+1 violates.

Two kinds of assertion, and the difference matters:

  * **the property** — a paged endpoint's statement count must not grow with its page. That
    holds for any implementation and will not need editing when one changes;
  * **an exact count against one table** — ``GET /resources/{path}`` may read
    ``ntfs_resources`` exactly twice, once for the directory and once for its parent. That is
    deliberately tight, because both duplicated reads Phase 3C removed were of exactly this
    shape: a row fetched, and then fetched again in the same request by a different layer
    that did not know it was already in hand.
"""

from __future__ import annotations

import re
import uuid
from typing import Any
from urllib.parse import quote

import pytest
import sqlalchemy as sa
from httpx import AsyncClient

from app.contracts.v1 import keys
from app.db import Database
from app.domain import AceType, AclAceFacts, Sid, acl_hash

pytestmark = pytest.mark.anyio

DOMAIN_SID = "S-1-5-21-1004336348-1177238915-682003330"
TRUSTEES = [
    "S-1-5-32-544",
    "S-1-5-11",
    f"{DOMAIN_SID}-1104",
    f"{DOMAIN_SID}-1202",
    f"{DOMAIN_SID}-1203",
    f"{DOMAIN_SID}-1204",
]
MODIFY = 0x001301BF

# Backslashes cannot appear inside an f-string expression on the pinned Python version, so
# the UNC spellings under test live here.
FINANCE_UNC = "\\\\FS01\\Finance"
FINANCE_KEY = "\\\\fs01\\finance"
REPORTS_UNC = "\\\\FS01\\Finance\\Reports"


def encoded(path: str) -> str:
    return quote(path, safe="")


class StatementLog:
    """Every statement one engine issues while the block is open.

    Attached to the engine rather than to a session so that nothing a request does can escape
    it — including a statement issued by a layer the test does not know about, which is
    exactly the kind an N+1 is made of.
    """

    def __init__(self, engine: Any) -> None:
        self._engine = engine.sync_engine if hasattr(engine, "sync_engine") else engine
        self.statements: list[str] = []

    def _record(self, conn: Any, cursor: Any, statement: str, *rest: Any) -> None:
        self.statements.append(" ".join(statement.split()))

    def __enter__(self) -> StatementLog:
        self.statements = []
        sa.event.listen(self._engine, "before_cursor_execute", self._record)
        return self

    def __exit__(self, *exc: object) -> None:
        sa.event.remove(self._engine, "before_cursor_execute", self._record)

    @property
    def count(self) -> int:
        return len(self.statements)

    def reading(self, table: str) -> int:
        """How many statements selected from one table.

        A crude match on ``FROM <table>`` and ``JOIN <table>``, which is enough: these
        queries are generated by one query builder and spell a table name one way. A count
        that is wrong because the match missed something would be wrong in the safe
        direction — too low, so a duplicated read would look like a single one and the test
        would fail rather than pass quietly.
        """
        pattern = re.compile(rf"\b(?:FROM|JOIN)\s+{re.escape(table)}\b", re.IGNORECASE)
        return sum(1 for statement in self.statements if pattern.search(statement))


@pytest.fixture
def statements(database: Database) -> StatementLog:
    return StatementLog(database.engine)


def observation(kind: str, run_id: str, index: int, **fields: Any) -> dict[str, Any]:
    return {
        "schema_version": "1.3",
        "kind": kind,
        "run_id": run_id,
        "observed_at": f"2026-09-14T08:{index % 60:02d}:00Z",
        **fields,
    }


def ace(run_id: str, index: int, path: str, trustee: str, order: int) -> dict[str, Any]:
    return observation(
        "ntfs_ace",
        run_id,
        index,
        source_key=keys.ntfs_ace_key(path, Sid(trustee), "allow", MODIFY, 0x03),
        path=path,
        trustee_sid=trustee,
        ace_type="allow",
        access_mask=MODIFY,
        ace_flags=0x03,
        source="explicit",
        order_index=order,
    )


def digest(entries: list[dict[str, Any]]) -> str:
    return acl_hash(
        dacl_present=True,
        dacl_protected=False,
        aces=[
            AclAceFacts(
                trustee_sid=item["trustee_sid"],
                ace_type=AceType(item["ace_type"]),
                access_mask=item["access_mask"],
                ace_flags=item["ace_flags"],
                order_index=item["order_index"],
            )
            for item in entries
        ],
    )


@pytest.fixture
async def estate(client: AsyncClient) -> None:
    """One server, several shares, and two directories with long ACLs.

    Long enough that a hundred-row page and a one-row page really are different sizes: an
    N+1 test against an ACL of two entries measures nothing.
    """
    run_id = str(uuid.uuid4())
    observations: list[dict[str, Any]] = [
        observation("server", run_id, 1, source_key=keys.server_key("FS01"), name="FS01")
    ]
    index = 2
    # Finance is in the list because the NTFS directories below are under it: the root-ACL
    # endpoint answers about the directory a share publishes, and a share whose root nothing
    # has described is a 404 rather than a measurement.
    for name in ["Finance", *(f"Share{number:02d}" for number in range(5))]:
        observations.append(
            observation(
                "smb_share",
                run_id,
                index,
                source_key=keys.share_key("FS01", name),
                server_name="FS01",
                share_name=name,
            )
        )
        index += 1
        for order, trustee in enumerate(TRUSTEES):
            observations.append(
                observation(
                    "smb_ace",
                    run_id,
                    index,
                    source_key=keys.smb_ace_key("FS01", name, Sid(trustee), "allow", None, "read"),
                    server_name="FS01",
                    share_name=name,
                    trustee_sid=trustee,
                    ace_type="allow",
                    permission="read",
                    order_index=order,
                )
            )
            index += 1

    for path, kind_fields in (
        (FINANCE_UNC, {"is_acl_boundary": True, "boundary_reason": "share_root"}),
        (REPORTS_UNC, {"is_acl_boundary": False}),
    ):
        entries = [
            ace(run_id, index + order, path, trustee, order)
            for order, trustee in enumerate(TRUSTEES)
        ]
        index += len(TRUSTEES)
        observations.append(
            observation(
                "ntfs_resource",
                run_id,
                index,
                source_key=keys.ntfs_resource_key(path),
                path=path,
                dacl_present=True,
                dacl_protected=False,
                ace_count=len(entries),
                acl_hash=digest(entries),
                **kind_fields,
            )
        )
        index += 1
        observations.extend(entries)

    for trustee in TRUSTEES:
        observations.append(
            observation(
                "principal",
                run_id,
                index,
                source_key=f"principal|{trustee}",
                sid=trustee,
                principal_kind="well_known" if trustee.startswith("S-1-5-32") else "user",
            )
        )
        index += 1

    transcript = {
        "start": {
            "schema_version": "1.3",
            "run_id": run_id,
            "source": {
                "collector": "ntfs",
                "collector_host": "COLLECTOR01",
                "method": "DirectorySecurity.GetSecurityDescriptorBinaryForm",
            },
            "started_at": "2026-09-14T08:00:00Z",
            "scopes": [{"kind": "directory_tree", "key": FINANCE_KEY}],
            "incremental": True,
        },
        "batches": [
            {
                "schema_version": "1.3",
                "run_id": run_id,
                "batch_id": str(uuid.uuid4()),
                "sequence": 1,
                "is_final": True,
                "observations": observations,
            }
        ],
        "completion": {
            "schema_version": "1.3",
            "run_id": run_id,
            "status": "succeeded",
            "completed_at": "2026-09-14T09:00:00Z",
            "batch_count": 1,
            "observation_count": len(observations),
            "error_count": 0,
            "errors": [],
            "reconciled_scopes": [],
        },
    }

    from tests.support.ingest import replay

    await replay(client, transcript)


PAGED = [
    pytest.param("/api/v1/servers?limit={n}", id="servers"),
    pytest.param("/api/v1/servers/FS01/shares?limit={n}", id="server-shares"),
    pytest.param("/api/v1/shares/fs01%7Cshare00/acl?limit={n}", id="share-acl"),
    pytest.param("/api/v1/shares/fs01%7Cfinance/root-acl?limit={n}", id="share-root-acl"),
    pytest.param(f"/api/v1/resources/{encoded(FINANCE_UNC)}/acl?limit={{n}}", id="resource-acl"),
    pytest.param("/api/v1/principals/S-1-5-11/shares?limit={n}", id="trustee-shares"),
]


@pytest.mark.parametrize("template", PAGED)
async def test_a_paged_read_costs_the_same_whatever_the_page_holds(
    client: AsyncClient, estate: None, statements: StatementLog, template: str
) -> None:
    """The N+1 property, stated as a property.

    A read whose statement count grows with its answer cannot be paged out of trouble: the
    hundredth row costs another round trip, and an estate is where that stops being free.
    """
    with statements:
        one = await client.get(template.format(n=1))
    single = statements.count

    with statements:
        many = await client.get(template.format(n=100))
    hundred = statements.count

    assert one.status_code == 200
    assert many.status_code == 200
    assert single > 0
    assert hundred == single, (
        f"{template} issued {single} statement(s) for one row and {hundred} for a hundred. "
        "A read's cost must not grow with the size of its answer."
    )


async def test_a_directory_detail_reads_the_resource_table_twice(
    client: AsyncClient, estate: None, statements: StatementLog
) -> None:
    """Once for the directory, once for its parent, and not again.

    The boundary verdict has to read the parent to project from it, and the response shows
    that same parent row. Before Phase 3C both layers fetched it independently, so this
    endpoint read the table three times to answer a question about two rows.
    """
    with statements:
        response = await client.get(f"/api/v1/resources/{encoded(REPORTS_UNC)}")

    assert response.status_code == 200
    assert response.json()["parent"] is not None
    assert statements.reading("ntfs_resources") == 2, (
        "GET /resources/{path} should read ntfs_resources once for the directory and once "
        f"for its parent; it read it {statements.reading('ntfs_resources')} times."
    )


async def test_a_share_root_acl_reads_the_resource_table_once(
    client: AsyncClient, estate: None, statements: StatementLog
) -> None:
    """The root is looked up to learn its key, and then not looked up again.

    It has to be read first — the share key alone does not say whether any run has described
    the directory the share publishes — and the ACL response then reports that same row.
    """
    with statements:
        response = await client.get("/api/v1/shares/fs01%7Cfinance/root-acl")

    assert response.status_code == 200
    assert statements.reading("ntfs_resources") == 1, (
        "GET /shares/{share}/root-acl should read ntfs_resources once; it read it "
        f"{statements.reading('ntfs_resources')} times."
    )


async def test_an_acl_page_reads_the_entry_table_a_bounded_number_of_times(
    client: AsyncClient, estate: None, statements: StatementLog
) -> None:
    """Three reads of ``ntfs_aces``: the page, the total, and the digest over the whole DACL.

    The third is unpaged on purpose — a digest over part of a DACL is not a digest of the
    DACL — and it is the reason this count is three rather than two. Pinned so that a fourth
    arriving unnoticed is a failure rather than a slow endpoint nobody can explain.
    """
    with statements:
        response = await client.get(f"/api/v1/resources/{encoded(FINANCE_UNC)}/acl?limit=2")

    assert response.status_code == 200
    assert statements.reading("ntfs_aces") == 3
