"""ADG permission domain model.

Canonical, framework-free types for identity, resources, raw permission facts, membership,
and provenance. They deliberately contain **no** permission-resolution algorithm: the
effective-access engine arrives in Phase 4 and consumes these types.

See `docs/architecture/permission-domain-model.md` for the semantics, and ADR-0001 through
ADR-0004 for the decisions these types encode.
"""

from __future__ import annotations

from app.domain.access import (
    FULL_CONTROL_MASK,
    GENERIC_RIGHT_BITS,
    SHARE_PERMISSION_MASKS,
    AceFlag,
    AceSource,
    AceType,
    AclLayer,
    NtfsAce,
    NtfsRight,
    SecurityDescriptorFacts,
    SharePermission,
    SmbShareAce,
    ntfs_ace_identity_key,
    share_ace_identity_key,
    share_ace_right_token,
)
from app.domain.acl_hash import (
    ACL_HASH_ALGORITHM,
    ACL_HASH_LENGTH,
    ACL_NORMAL_FORM_VERSION,
    AclAceFacts,
    NormalizedAcl,
    acl_hash,
    is_acl_hash,
    normalize_acl,
)
from app.domain.errors import DomainError, DomainValidationError
from app.domain.graph import (
    DEFAULT_LIMITS,
    MAX_DEPTH_CEILING,
    MAX_EDGES_CEILING,
    MAX_NODES_CEILING,
    MAX_PATHS_CEILING,
    AdjacencyProvider,
    Direction,
    Expansion,
    GraphCycle,
    GraphEdge,
    MembershipPath,
    PathSearch,
    ReachedNode,
    TraversalLimits,
    TruncationReason,
    expand,
    find_cycles,
    find_paths,
)
from app.domain.identity import (
    MAX_SUB_AUTHORITIES,
    WELL_KNOWN_RID_NAMES,
    WELL_KNOWN_SID_NAMES,
    ComputerIdentity,
    DomainGroup,
    DomainIdentifier,
    DomainKind,
    GroupScope,
    GroupType,
    LocalGroup,
    Principal,
    PrincipalKind,
    Sid,
    UnresolvedPrincipal,
    UnresolvedReason,
    User,
    WellKnownPrincipal,
    referenced_principal_key,
)
from app.domain.inheritance import (
    SUBSTITUTED_TRUSTEES,
    AclBoundaryReason,
    boundary_reason_for,
    inherited_child_acl_hash,
    map_generic_rights,
    project_inherited_ace,
    project_inherited_ace_flags,
    project_inherited_acl,
    projected_child_acl,
)
from app.domain.membership import MembershipEdge, MembershipEdgeKind
from app.domain.observation import (
    CollectorKind,
    Observation,
    ObservationSource,
    ScanRun,
    ScanStatus,
)
from app.domain.paths import (
    LocalPath,
    UncPath,
    parse_local_path,
    parse_unc_path,
    parse_windows_path,
)
from app.domain.resources import (
    DirectoryResource,
    ResourceKind,
    Server,
    ShareIdentity,
    ShareType,
    SmbShare,
    parse_share_identifier,
)

__all__ = [
    "ACL_HASH_ALGORITHM",
    "ACL_HASH_LENGTH",
    "ACL_NORMAL_FORM_VERSION",
    "DEFAULT_LIMITS",
    "FULL_CONTROL_MASK",
    "GENERIC_RIGHT_BITS",
    "MAX_DEPTH_CEILING",
    "MAX_EDGES_CEILING",
    "MAX_NODES_CEILING",
    "MAX_PATHS_CEILING",
    "MAX_SUB_AUTHORITIES",
    "SHARE_PERMISSION_MASKS",
    "SUBSTITUTED_TRUSTEES",
    "WELL_KNOWN_RID_NAMES",
    "WELL_KNOWN_SID_NAMES",
    "AceFlag",
    "AceSource",
    "AceType",
    "AclAceFacts",
    "AclBoundaryReason",
    "AclLayer",
    "AdjacencyProvider",
    "CollectorKind",
    "ComputerIdentity",
    "Direction",
    "DirectoryResource",
    "DomainError",
    "DomainGroup",
    "DomainIdentifier",
    "DomainKind",
    "DomainValidationError",
    "Expansion",
    "GraphCycle",
    "GraphEdge",
    "GroupScope",
    "GroupType",
    "LocalGroup",
    "LocalPath",
    "MembershipEdge",
    "MembershipEdgeKind",
    "MembershipPath",
    "NormalizedAcl",
    "NtfsAce",
    "NtfsRight",
    "Observation",
    "ObservationSource",
    "PathSearch",
    "Principal",
    "PrincipalKind",
    "ReachedNode",
    "ResourceKind",
    "ScanRun",
    "ScanStatus",
    "SecurityDescriptorFacts",
    "Server",
    "ShareIdentity",
    "SharePermission",
    "ShareType",
    "Sid",
    "SmbShare",
    "SmbShareAce",
    "TraversalLimits",
    "TruncationReason",
    "UncPath",
    "UnresolvedPrincipal",
    "UnresolvedReason",
    "User",
    "WellKnownPrincipal",
    "acl_hash",
    "boundary_reason_for",
    "expand",
    "find_cycles",
    "find_paths",
    "inherited_child_acl_hash",
    "is_acl_hash",
    "map_generic_rights",
    "normalize_acl",
    "ntfs_ace_identity_key",
    "parse_local_path",
    "parse_share_identifier",
    "parse_unc_path",
    "parse_windows_path",
    "project_inherited_ace",
    "project_inherited_ace_flags",
    "project_inherited_acl",
    "projected_child_acl",
    "referenced_principal_key",
    "share_ace_identity_key",
    "share_ace_right_token",
]
