"""ADG permission domain model.

Canonical, framework-free types for identity, resources, raw permission facts, membership,
and provenance. They deliberately contain **no** permission-resolution algorithm: the
effective-access engine arrives in Phase 4 and consumes these types.

See `docs/architecture/permission-domain-model.md` for the semantics, and ADR-0001 through
ADR-0004 for the decisions these types encode.
"""

from __future__ import annotations

from app.domain.access import (
    FULL_CONTROL_MASK,
    GENERIC_RIGHT_BITS,
    SHARE_PERMISSION_MASKS,
    AceFlag,
    AceSource,
    AceType,
    AclLayer,
    NtfsAce,
    NtfsRight,
    SecurityDescriptorFacts,
    SharePermission,
    SmbShareAce,
)
from app.domain.errors import DomainError, DomainValidationError
from app.domain.graph import (
    DEFAULT_LIMITS,
    MAX_DEPTH_CEILING,
    MAX_EDGES_CEILING,
    MAX_NODES_CEILING,
    MAX_PATHS_CEILING,
    AdjacencyProvider,
    Direction,
    Expansion,
    GraphCycle,
    GraphEdge,
    MembershipPath,
    PathSearch,
    ReachedNode,
    TraversalLimits,
    TruncationReason,
    expand,
    find_cycles,
    find_paths,
)
from app.domain.identity import (
    MAX_SUB_AUTHORITIES,
    WELL_KNOWN_RID_NAMES,
    WELL_KNOWN_SID_NAMES,
    ComputerIdentity,
    DomainGroup,
    DomainIdentifier,
    DomainKind,
    GroupScope,
    GroupType,
    LocalGroup,
    Principal,
    PrincipalKind,
    Sid,
    UnresolvedPrincipal,
    UnresolvedReason,
    User,
    WellKnownPrincipal,
)
from app.domain.membership import MembershipEdge, MembershipEdgeKind
from app.domain.observation import (
    CollectorKind,
    Observation,
    ObservationSource,
    ScanRun,
    ScanStatus,
)
from app.domain.paths import (
    LocalPath,
    UncPath,
    parse_local_path,
    parse_unc_path,
    parse_windows_path,
)
from app.domain.resources import DirectoryResource, Server, ShareType, SmbShare

__all__ = [
    "DEFAULT_LIMITS",
    "FULL_CONTROL_MASK",
    "GENERIC_RIGHT_BITS",
    "MAX_DEPTH_CEILING",
    "MAX_EDGES_CEILING",
    "MAX_NODES_CEILING",
    "MAX_PATHS_CEILING",
    "MAX_SUB_AUTHORITIES",
    "SHARE_PERMISSION_MASKS",
    "WELL_KNOWN_RID_NAMES",
    "WELL_KNOWN_SID_NAMES",
    "AceFlag",
    "AceSource",
    "AceType",
    "AclLayer",
    "AdjacencyProvider",
    "CollectorKind",
    "ComputerIdentity",
    "Direction",
    "DirectoryResource",
    "DomainError",
    "DomainGroup",
    "DomainIdentifier",
    "DomainKind",
    "DomainValidationError",
    "Expansion",
    "GraphCycle",
    "GraphEdge",
    "GroupScope",
    "GroupType",
    "LocalGroup",
    "LocalPath",
    "MembershipEdge",
    "MembershipEdgeKind",
    "MembershipPath",
    "NtfsAce",
    "NtfsRight",
    "Observation",
    "ObservationSource",
    "PathSearch",
    "Principal",
    "PrincipalKind",
    "ReachedNode",
    "ScanRun",
    "ScanStatus",
    "SecurityDescriptorFacts",
    "Server",
    "SharePermission",
    "ShareType",
    "Sid",
    "SmbShare",
    "SmbShareAce",
    "TraversalLimits",
    "TruncationReason",
    "UncPath",
    "UnresolvedPrincipal",
    "UnresolvedReason",
    "User",
    "WellKnownPrincipal",
    "expand",
    "find_cycles",
    "find_paths",
    "parse_local_path",
    "parse_unc_path",
    "parse_windows_path",
]
