"""Scan-run envelopes: start, batch, completion.

The three envelopes define the whole collector protocol, and between them they carry the
two properties that make ingestion safe:

* **Idempotency.** ``run_id`` and ``batch_id`` are generated by the collector and reused on
  retry, so a re-sent start, batch, or completion is recognized rather than duplicated.
* **Absence is never inferred from silence.** An object missing from a batch means nothing.
  Only a *reconciled* scope on a successful, non-incremental run authorizes marking
  anything absent — which is why :class:`ScanRunCompletion` refuses to carry reconciled
  scopes for a partial, failed, canceled, or error-bearing run.

See `docs/contracts/collector-protocol.md` for the sequence a collector follows.
"""

from __future__ import annotations

from collections import Counter
from typing import Annotated, Literal, Self

from pydantic import AwareDatetime, Field, model_validator

from app.contracts.v1.common import (
    MAX_BATCH_AFFIRMATIONS,
    MAX_BATCH_OBSERVATIONS,
    SCHEMA_VERSION,
    Affirmation,
    CollectorCheckpoint,
    ContractModel,
    Scope,
    SourceDescriptor,
    schema_minor,
    to_utc,
)
from app.contracts.v1.observations import (
    MembershipObservation,
    NtfsAceObservation,
    NtfsResourceObservation,
    PrincipalObservation,
    ServerObservation,
    SmbAceObservation,
    SmbShareObservation,
)
from app.domain import CollectionMode, ScanRun, ScanStatus

ObservationUnion = Annotated[
    PrincipalObservation
    | MembershipObservation
    | ServerObservation
    | SmbShareObservation
    | SmbAceObservation
    | NtfsResourceObservation
    | NtfsAceObservation,
    Field(discriminator="kind"),
]


class ScanRunStart(ContractModel):
    """Opens a scan run.

    Re-posting an identical start is a no-op that returns the existing run: the collector
    owns ``run_id``, so a retry after a timeout cannot create a second run.
    """

    schema_version: str = SCHEMA_VERSION
    run_id: str
    source: SourceDescriptor
    started_at: AwareDatetime
    scopes: list[Scope] = Field(min_length=1, max_length=1000)
    incremental: bool = False
    notes: str | None = Field(default=None, max_length=2000)
    mode: CollectionMode | None = Field(
        default=None,
        description=(
            "Contract 1.4. Why this run is or is not incremental: 'full', 'delta', or "
            "'reconcile'. Omitted by collectors predating 1.4, in which case it is derived "
            "from `incremental` and means the same thing less precisely."
        ),
    )
    job: str | None = Field(
        default=None,
        max_length=128,
        description=(
            "Contract 1.4. The scheduled job this run belongs to, as named in the "
            "orchestrator configuration. Free-form: the server groups and reports by it and "
            "never interprets it."
        ),
    )
    baseline: CollectorCheckpoint | None = Field(
        default=None,
        description=(
            "Contract 1.4. The checkpoint this delta resumed from. Recorded so that a "
            "later gap can be attributed: without it, a run that resumed from a watermark "
            "nobody kept is indistinguishable from one that read everything."
        ),
    )

    @model_validator(mode="after")
    def _normalize(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_version(self.schema_version)
        object.__setattr__(self, "started_at", to_utc(self.started_at))
        keys = [f"{scope.kind.value}|{scope.key}" for scope in self.scopes]
        if len(set(keys)) != len(keys):
            raise ValueError(
                "A run must declare each scope once; duplicates make coverage ambiguous."
            )
        _require_minor(self.schema_version, 4, mode=self.mode, job=self.job, baseline=self.baseline)

        if self.mode is None:
            # Derived rather than defaulted to `full`: a 1.3 collector setting
            # `incremental: true` is making the delta claim in the only vocabulary it has,
            # and recording that run as `full` would file it beside runs that read
            # everything.
            mode = CollectionMode.DELTA if self.incremental else CollectionMode.FULL
            object.__setattr__(self, "mode", mode)
        elif self.mode.is_incremental != self.incremental:
            raise ValueError(
                f"mode {self.mode.value!r} and incremental={self.incremental} contradict "
                "each other. `incremental` is the flag that decides whether this run may "
                "ever mark an object absent, and `mode` says why; a payload where they "
                "disagree does not state which one the server should act on."
            )

        resolved = self.mode
        # Set just above when it was absent, so it is never None here; the assertion is
        # what tells the type checker so.
        assert resolved is not None
        if self.baseline is not None and not resolved.is_incremental:
            raise ValueError(
                f"A {resolved.value} run resumes from nothing: it reads its whole scope, "
                "so a baseline checkpoint would record a starting point it did not start "
                "from. Send the baseline only on a delta run."
            )
        return self

    def to_domain(self) -> ScanRun:
        """Build the running domain scan run this envelope opens."""
        from uuid import UUID

        return ScanRun(
            source=self.source.to_domain(),
            started_at=self.started_at,
            run_id=UUID(self.run_id),
            status=ScanStatus.RUNNING,
        )


class ObservationBatch(ContractModel):
    """A chunk of observations belonging to one run.

    The batch is the unit of retry. A server that has already applied ``batch_id`` for this
    run acknowledges it again without re-applying, and every observation is keyed by
    ``(run_id, source_key)`` so even an un-deduplicated replay converges on the same state.
    """

    schema_version: str = SCHEMA_VERSION
    run_id: str
    batch_id: str
    sequence: int = Field(ge=1)
    is_final: bool = False
    continuation_token: str | None = Field(default=None, max_length=2048)
    # `min_length` is 0 only so that a batch may carry affirmations alone; a batch with
    # neither is still rejected below, so a 1.0-1.3 payload is held to exactly the rule it
    # was written against.
    observations: list[ObservationUnion] = Field(
        default_factory=list, max_length=MAX_BATCH_OBSERVATIONS
    )
    affirmations: list[Affirmation] = Field(
        default_factory=list,
        max_length=MAX_BATCH_AFFIRMATIONS,
        description=(
            "Contract 1.4. Objects this scan re-read and found unchanged, sent as a key and "
            "a digest instead of the whole object. The server verifies each digest against "
            "what it holds and refuses the ones that disagree."
        ),
    )
    checkpoint: CollectorCheckpoint | None = Field(
        default=None,
        description=(
            "Contract 1.4. The cursor covering everything in and before this batch. The "
            "server advances the job's stored checkpoint to it only once the batch has been "
            "applied, so a batch that never arrived cannot move the resume point past it."
        ),
    )

    @model_validator(mode="after")
    def _check_consistency(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_uuid(self.batch_id, "batch_id")
        _require_version(self.schema_version)
        _require_minor(
            self.schema_version,
            4,
            affirmations=self.affirmations or None,
            checkpoint=self.checkpoint,
        )

        if not self.observations and not self.affirmations:
            raise ValueError(
                "A batch must carry at least one observation or affirmation. An empty batch "
                "consumes a batch_id and a sequence number and tells the server nothing, so "
                "it would count towards coverage without contributing any."
            )

        mismatched = {observation.run_id for observation in self.observations} - {self.run_id}
        if mismatched:
            raise ValueError(
                f"Every observation must carry the batch's run_id ({self.run_id}); found "
                f"{sorted(mismatched)}. Mixing runs in one batch would attribute "
                "observations to a run that never claimed their scope."
            )

        # Counter, not `list.count` per element: this runs on every batch POST, and a
        # 1,000-observation batch is the contract's maximum, so the quadratic form spends
        # a million string comparisons per batch to answer a question one pass settles.
        seen = Counter(observation.source_key for observation in self.observations)
        duplicates = sorted(key for key, count in seen.items() if count > 1)
        if duplicates:
            raise ValueError(
                f"A batch must not contain the same source_key twice; found {duplicates}. "
                "Two observations with one key are indistinguishable, so the second would "
                "silently overwrite the first."
            )

        affirmed = Counter(affirmation.source_key for affirmation in self.affirmations)
        repeated = sorted(key for key, count in affirmed.items() if count > 1)
        if repeated:
            raise ValueError(
                f"A batch must not affirm the same source_key twice; found {repeated}."
            )
        contradicted = sorted(set(affirmed) & set(seen))
        if contradicted:
            raise ValueError(
                f"A batch both observes and affirms {contradicted}. One says the object's "
                "state is what this payload carries and the other says it is whatever the "
                "server already holds, and nothing in the batch says which reading the "
                "collector actually took. Send the object once, either way."
            )
        return self

    @property
    def source_keys(self) -> list[str]:
        return [observation.source_key for observation in self.observations]

    @property
    def affirmed_keys(self) -> list[str]:
        return [affirmation.source_key for affirmation in self.affirmations]

    @property
    def item_count(self) -> int:
        """Everything in this batch that names an object, affirmed or observed."""
        return len(self.observations) + len(self.affirmations)


class CollectorError(ContractModel):
    """A failure the collector hit. Reported, never silently swallowed."""

    code: str = Field(min_length=1, max_length=64)
    message: str = Field(min_length=1, max_length=2000)
    target: str | None = Field(default=None, max_length=1024)
    occurred_at: AwareDatetime | None = None


class ScanRunCompletion(ContractModel):
    """Closes a run and optionally reconciles the scopes it fully enumerated."""

    schema_version: str = SCHEMA_VERSION
    run_id: str
    status: Literal["succeeded", "partial", "failed", "canceled"]
    completed_at: AwareDatetime
    batch_count: int = Field(ge=0)
    observation_count: int = Field(ge=0)
    error_count: int = Field(default=0, ge=0)
    errors: list[CollectorError] = Field(default_factory=list, max_length=1000)
    reconciled_scopes: list[Scope] = Field(default_factory=list, max_length=1000)
    notes: str | None = Field(default=None, max_length=2000)
    affirmation_count: int = Field(
        default=0,
        ge=0,
        description=(
            "Contract 1.4. How many affirmations the collector sent, counted the way "
            "`observation_count` counts observations."
        ),
    )
    checkpoint: CollectorCheckpoint | None = Field(
        default=None,
        description=(
            "Contract 1.4. The cursor the next delta may resume from. Permitted only on a "
            "run that succeeded: see the validator."
        ),
    )

    @model_validator(mode="after")
    def _check_consistency(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_version(self.schema_version)
        object.__setattr__(self, "completed_at", to_utc(self.completed_at))
        _require_minor(
            self.schema_version,
            4,
            affirmation_count=self.affirmation_count or None,
            checkpoint=self.checkpoint,
        )

        if self.checkpoint is not None and (self.status != "succeeded" or self.error_count):
            raise ValueError(
                f"A {self.status} run with {self.error_count} error(s) must not record a "
                "checkpoint. The cursor would claim everything below it had been read, and "
                "the next delta would start above exactly the objects this run failed on — "
                "a gap that closes only by accident, because nothing afterwards looks "
                "missing."
            )

        if self.errors and self.error_count < len(self.errors):
            raise ValueError(
                f"error_count ({self.error_count}) is smaller than the number of reported "
                f"errors ({len(self.errors)}); coverage would look better than it is."
            )
        if self.status == "succeeded" and self.error_count:
            raise ValueError(
                "A run that hit errors is 'partial' or 'failed', never 'succeeded'. "
                "Reporting complete coverage that was not achieved understates access."
            )
        if self.reconciled_scopes and (self.status != "succeeded" or self.error_count):
            raise ValueError(
                f"A {self.status} run with {self.error_count} error(s) must not reconcile "
                "any scope. Objects it did not observe may still exist, and marking them "
                "absent would delete real access from the record."
            )
        return self

    @property
    def domain_status(self) -> ScanStatus:
        return ScanStatus(self.status)

    @property
    def may_reconcile(self) -> bool:
        """Whether this completion authorizes inferring absence anywhere."""
        return bool(self.reconciled_scopes)

    def reconciles(self, start: ScanRunStart) -> bool:
        """Whether every reconciled scope was actually declared at start.

        A run cannot reconcile a scope it never claimed to enumerate, and an incremental
        run cannot reconcile at all: it deliberately re-read only part of its scopes.
        """
        if not self.reconciled_scopes:
            return True
        if start.incremental:
            return False
        declared = {(scope.kind, scope.key) for scope in start.scopes}
        return all((scope.kind, scope.key) in declared for scope in self.reconciled_scopes)

    def to_domain(self, start: ScanRunStart) -> ScanRun:
        """Build the completed domain scan run described by this envelope."""
        from uuid import UUID

        return ScanRun(
            source=start.source.to_domain(),
            started_at=start.started_at,
            run_id=UUID(self.run_id),
            status=self.domain_status,
            completed_at=self.completed_at,
            observation_count=self.observation_count,
            error_count=self.error_count,
            notes=self.notes,
        )


def _require_uuid(value: str, field_name: str) -> None:
    from app.contracts.v1.common import _validate_uuid

    _validate_uuid(value, field_name=field_name)


def _require_minor(version: str, minor: int, **fields: object) -> None:
    """Refuse a field that a payload's declared minor version predates.

    A rule a later minor introduces applies only to payloads claiming that minor — that is
    what makes the bump additive. This is the mirror image: a payload claiming an *earlier*
    minor may not use a field that minor had never heard of. Without the check, a collector
    that declares ``1.0`` and sends a checkpoint would have it stored, and the version
    string would stop meaning anything about what the payload can contain.

    Pass ``None`` for a field that is absent; an empty list counts as absent, because
    sending none of something is what every earlier minor does.
    """
    if schema_minor(version) >= minor:
        return
    used = sorted(name for name, value in fields.items() if value is not None)
    if not used:
        return
    plural = "s" if len(used) > 1 else ""
    raise ValueError(
        f"Field{plural} {', '.join(used)} {'were' if len(used) > 1 else 'was'} introduced "
        f"in contract 1.{minor}, and this payload declares schema_version {version!r}. "
        f"Either declare 1.{minor} or omit {'them' if len(used) > 1 else 'it'}; a payload "
        "whose version does not cover its own fields cannot be validated against the "
        "contract it names."
    )


def _require_version(value: str) -> None:
    from app.contracts.v1.common import SCHEMA_VERSION_PATTERN

    if not SCHEMA_VERSION_PATTERN.match(value):
        raise ValueError(
            f"Unsupported schema_version {value!r}. This endpoint speaks contract v1 "
            f"(current {SCHEMA_VERSION})."
        )
