"""Scan-run envelopes: start, batch, completion.

The three envelopes define the whole collector protocol, and between them they carry the
two properties that make ingestion safe:

* **Idempotency.** ``run_id`` and ``batch_id`` are generated by the collector and reused on
  retry, so a re-sent start, batch, or completion is recognized rather than duplicated.
* **Absence is never inferred from silence.** An object missing from a batch means nothing.
  Only a *reconciled* scope on a successful, non-incremental run authorizes marking
  anything absent — which is why :class:`ScanRunCompletion` refuses to carry reconciled
  scopes for a partial, failed, canceled, or error-bearing run.

See `docs/contracts/collector-protocol.md` for the sequence a collector follows.
"""

from __future__ import annotations

from collections import Counter
from typing import Annotated, Literal, Self

from pydantic import AwareDatetime, Field, model_validator

from app.contracts.v1.common import (
    MAX_BATCH_OBSERVATIONS,
    SCHEMA_VERSION,
    ContractModel,
    Scope,
    SourceDescriptor,
    to_utc,
)
from app.contracts.v1.observations import (
    MembershipObservation,
    NtfsAceObservation,
    NtfsResourceObservation,
    PrincipalObservation,
    ServerObservation,
    SmbAceObservation,
    SmbShareObservation,
)
from app.domain import ScanRun, ScanStatus

ObservationUnion = Annotated[
    PrincipalObservation
    | MembershipObservation
    | ServerObservation
    | SmbShareObservation
    | SmbAceObservation
    | NtfsResourceObservation
    | NtfsAceObservation,
    Field(discriminator="kind"),
]


class ScanRunStart(ContractModel):
    """Opens a scan run.

    Re-posting an identical start is a no-op that returns the existing run: the collector
    owns ``run_id``, so a retry after a timeout cannot create a second run.
    """

    schema_version: str = SCHEMA_VERSION
    run_id: str
    source: SourceDescriptor
    started_at: AwareDatetime
    scopes: list[Scope] = Field(min_length=1, max_length=1000)
    incremental: bool = False
    notes: str | None = Field(default=None, max_length=2000)

    @model_validator(mode="after")
    def _normalize(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_version(self.schema_version)
        object.__setattr__(self, "started_at", to_utc(self.started_at))
        keys = [f"{scope.kind.value}|{scope.key}" for scope in self.scopes]
        if len(set(keys)) != len(keys):
            raise ValueError(
                "A run must declare each scope once; duplicates make coverage ambiguous."
            )
        return self

    def to_domain(self) -> ScanRun:
        """Build the running domain scan run this envelope opens."""
        from uuid import UUID

        return ScanRun(
            source=self.source.to_domain(),
            started_at=self.started_at,
            run_id=UUID(self.run_id),
            status=ScanStatus.RUNNING,
        )


class ObservationBatch(ContractModel):
    """A chunk of observations belonging to one run.

    The batch is the unit of retry. A server that has already applied ``batch_id`` for this
    run acknowledges it again without re-applying, and every observation is keyed by
    ``(run_id, source_key)`` so even an un-deduplicated replay converges on the same state.
    """

    schema_version: str = SCHEMA_VERSION
    run_id: str
    batch_id: str
    sequence: int = Field(ge=1)
    is_final: bool = False
    continuation_token: str | None = Field(default=None, max_length=2048)
    observations: list[ObservationUnion] = Field(min_length=1, max_length=MAX_BATCH_OBSERVATIONS)

    @model_validator(mode="after")
    def _check_consistency(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_uuid(self.batch_id, "batch_id")
        _require_version(self.schema_version)

        mismatched = {observation.run_id for observation in self.observations} - {self.run_id}
        if mismatched:
            raise ValueError(
                f"Every observation must carry the batch's run_id ({self.run_id}); found "
                f"{sorted(mismatched)}. Mixing runs in one batch would attribute "
                "observations to a run that never claimed their scope."
            )

        # Counter, not `list.count` per element: this runs on every batch POST, and a
        # 1,000-observation batch is the contract's maximum, so the quadratic form spends
        # a million string comparisons per batch to answer a question one pass settles.
        seen = Counter(observation.source_key for observation in self.observations)
        duplicates = sorted(key for key, count in seen.items() if count > 1)
        if duplicates:
            raise ValueError(
                f"A batch must not contain the same source_key twice; found {duplicates}. "
                "Two observations with one key are indistinguishable, so the second would "
                "silently overwrite the first."
            )
        return self

    @property
    def source_keys(self) -> list[str]:
        return [observation.source_key for observation in self.observations]


class CollectorError(ContractModel):
    """A failure the collector hit. Reported, never silently swallowed."""

    code: str = Field(min_length=1, max_length=64)
    message: str = Field(min_length=1, max_length=2000)
    target: str | None = Field(default=None, max_length=1024)
    occurred_at: AwareDatetime | None = None


class ScanRunCompletion(ContractModel):
    """Closes a run and optionally reconciles the scopes it fully enumerated."""

    schema_version: str = SCHEMA_VERSION
    run_id: str
    status: Literal["succeeded", "partial", "failed", "canceled"]
    completed_at: AwareDatetime
    batch_count: int = Field(ge=0)
    observation_count: int = Field(ge=0)
    error_count: int = Field(default=0, ge=0)
    errors: list[CollectorError] = Field(default_factory=list, max_length=1000)
    reconciled_scopes: list[Scope] = Field(default_factory=list, max_length=1000)
    notes: str | None = Field(default=None, max_length=2000)

    @model_validator(mode="after")
    def _check_consistency(self) -> Self:
        _require_uuid(self.run_id, "run_id")
        _require_version(self.schema_version)
        object.__setattr__(self, "completed_at", to_utc(self.completed_at))

        if self.errors and self.error_count < len(self.errors):
            raise ValueError(
                f"error_count ({self.error_count}) is smaller than the number of reported "
                f"errors ({len(self.errors)}); coverage would look better than it is."
            )
        if self.status == "succeeded" and self.error_count:
            raise ValueError(
                "A run that hit errors is 'partial' or 'failed', never 'succeeded'. "
                "Reporting complete coverage that was not achieved understates access."
            )
        if self.reconciled_scopes and (self.status != "succeeded" or self.error_count):
            raise ValueError(
                f"A {self.status} run with {self.error_count} error(s) must not reconcile "
                "any scope. Objects it did not observe may still exist, and marking them "
                "absent would delete real access from the record."
            )
        return self

    @property
    def domain_status(self) -> ScanStatus:
        return ScanStatus(self.status)

    @property
    def may_reconcile(self) -> bool:
        """Whether this completion authorizes inferring absence anywhere."""
        return bool(self.reconciled_scopes)

    def reconciles(self, start: ScanRunStart) -> bool:
        """Whether every reconciled scope was actually declared at start.

        A run cannot reconcile a scope it never claimed to enumerate, and an incremental
        run cannot reconcile at all: it deliberately re-read only part of its scopes.
        """
        if not self.reconciled_scopes:
            return True
        if start.incremental:
            return False
        declared = {(scope.kind, scope.key) for scope in start.scopes}
        return all((scope.kind, scope.key) in declared for scope in self.reconciled_scopes)

    def to_domain(self, start: ScanRunStart) -> ScanRun:
        """Build the completed domain scan run described by this envelope."""
        from uuid import UUID

        return ScanRun(
            source=start.source.to_domain(),
            started_at=start.started_at,
            run_id=UUID(self.run_id),
            status=self.domain_status,
            completed_at=self.completed_at,
            observation_count=self.observation_count,
            error_count=self.error_count,
            notes=self.notes,
        )


def _require_uuid(value: str, field_name: str) -> None:
    from app.contracts.v1.common import _validate_uuid

    _validate_uuid(value, field_name=field_name)


def _require_version(value: str) -> None:
    from app.contracts.v1.common import SCHEMA_VERSION_PATTERN

    if not SCHEMA_VERSION_PATTERN.match(value):
        raise ValueError(
            f"Unsupported schema_version {value!r}. This endpoint speaks contract v1 "
            f"(current {SCHEMA_VERSION})."
        )
